import { NgModule } from '@angular/core';
import {
  MatGridListModule,
  MatDatepickerModule,
  MatButtonModule,
  MatFormFieldModule,
  MatInputModule,
  MatAutocompleteModule,
  MatChipsModule,
  MatIconModule,
  MatSortModule,
  MatTableModule,
  MatPaginatorModule,
  MatSlideToggleModule,
  MatSliderModule,
  MatSelectModule,
  MatNativeDateModule,
  MatRadioModule,
  MatMenuModule,
  MatCheckboxModule,
  MatStepperModule,
  MatBottomSheetModule,
  MatTooltipModule,
  MatDialogModule,
  MatProgressBarModule,
  MatExpansionModule,
  MatDividerModule,
  MatSnackBarModule,
  MatCardModule
} from '@angular/material';

@NgModule({
  imports: [
    MatSlideToggleModule,
    MatSliderModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatAutocompleteModule,
    MatTableModule,
    MatSortModule,
    MatIconModule,
    MatButtonModule,
    MatRadioModule,
    MatInputModule,
    MatMenuModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatStepperModule,
    MatChipsModule,
    MatBottomSheetModule,
    MatPaginatorModule,
    MatTooltipModule,
    MatDialogModule,
    MatProgressBarModule,
    MatExpansionModule,
    MatDividerModule,
    MatSnackBarModule,
    MatGridListModule,
    MatCardModule
  ],
  exports: [
    MatSlideToggleModule,
    MatSliderModule,
    MatSelectModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatAutocompleteModule,
    MatTableModule,
    MatSortModule,
    MatIconModule,
    MatButtonModule,
    MatRadioModule,
    MatInputModule,
    MatMenuModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatStepperModule,
    MatChipsModule,
    MatBottomSheetModule,
    MatPaginatorModule,
    MatTooltipModule,
    MatDialogModule,
    MatProgressBarModule,
    MatExpansionModule,
    MatDividerModule,
    MatSnackBarModule,
    MatGridListModule,
    MatCardModule
  ],

  declarations: []
})
export class AngularMaterialModule {}
